version: "3.8"

services:
  log-server:
    build: ./log_server
    container_name: log-server
    ports:
      - "8082:8082"
    volumes:
      - ./log_server/data:/data          
    environment:
      - SPRING_APPLICATION_NAME=log_server
      - SERVER_PORT=8082
      # ensure server writes logs.jsonl in /data
      - LOG_FILE_PATH=/data/logs.jsonl

  log-collector:
    build: ./log-collector
    container_name: log-collector
    depends_on:
      - log-server
    ports:
      - "9000:9000"    # TCP listener you used
    environment:
      - SPRING_APPLICATION_NAME=log-collector
      - collector.port=9000
      - collector.protocol=tcp
      # service name used by composer: log-server
      - log_server.url=http://log-server:8082

  windows-client:
    build: ./windows-client
    container_name: windows-client
    depends_on:
      - log-collector
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=windows-client
      - SERVER_PORT=8090
      - collector.host=log-collector
      - collector.port=9000
      - collector.protocol=tcp
